httpd-config: |
  <VirtualHost *:80>
      ServerAdmin webmaster@dummy-host.example.com
      DocumentRoot /vagrant/www/public
      ErrorLog /vagrant/logs/development-error_log
      CustomLog /vagrant/logs/development-access_log common
      <directory /vagrant/www/public>
          Options All
          Order deny,allow
          Allow from all
          AllowOverride all
          <IfModule authz_core>
            ###httpdRequire###
          </IfModule>
      </directory>
  </VirtualHost>
vagrantfile: |
  Vagrant.configure("2") do |config|
    config.vm.box = "###box###"
    config.vm.synced_folder "./", "/vagrant"
    config.vm.provider "virtualbox" do |v, override|
      v.name = "###name###"
      override.vm.synced_folder "./", "/vagrant", owner: 'vagrant', group: '###group###'
    end
    config.vm.provider "parallels" do |v, override|
      v.name = "###name###"
      v.update_guest_tools = true
      override.vm.synced_folder "./", "/vagrant"
    end
    $script = <<SCRIPT
  ###script###
  SCRIPT
    config.vm.provision "shell", inline: $script
    config.vm.network "private_network", ip: "192.168.33.###IP###"
  end
php-config: |
    date.timezone = "Europe/London";
